[package]
name = "mox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
rayon = "1.10.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "sync"] }
